import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e6deff",
        "surface-bright": "#373943",
        "surface": "#11131c",
        "on-tertiary-fixed-variant": "#454651",
        "tertiary-container": "#adadba",
        "surface-container": "#1d1f29",
        "surface-tint": "#4cddb7",
        "inverse-primary": "#006b55",
        "outline-variant": "#3c4a44",
        "inverse-surface": "#e1e1ef",
        "surface-dim": "#11131c",
        "on-secondary-fixed-variant": "#4927b6",
        "primary-fixed": "#6efad2",
        "secondary-container": "#4b2ab8",
        "on-primary-fixed": "#002118",
        "on-tertiary": "#2e303a",
        "on-secondary": "#32009a",
        "primary-container": "#27c49f",
        "on-background": "#e1e1ef",
        "tertiary-fixed-dim": "#c5c5d2",
        "outline": "#85948d",
        "on-tertiary-container": "#3f414b",
        "on-primary-fixed-variant": "#00513f",
        "on-tertiary-fixed": "#191b24",
        "on-secondary-fixed": "#1c0062",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#cabeff",
        "tertiary-fixed": "#e1e1ef",
        "on-surface": "#e1e1ef",
        "surface-container-low": "#191b25",
        "error-container": "#93000a",
        "on-primary-container": "#004b3b",
        "surface-container-lowest": "#0c0e17",
        "on-primary": "#00382b",
        "primary-fixed-dim": "#4cddb7",
        "primary": "#50e0ba",
        "error": "#ffb4ab",
        "inverse-on-surface": "#2e303a",
        "background": "#11131c",
        "on-error": "#690005",
        "on-secondary-container": "#bcaeff",
        "surface-container-highest": "#32343f",
        "secondary": "#cabeff",
        "surface-container-high": "#272934",
        "on-surface-variant": "#bbcac3",
        "surface-variant": "#32343f",
        "tertiary": "#c8c8d5",
        // Keep old colors as variables fallback so we don't break other pages
        "panel": "rgb(var(--panel) / <alpha-value>)",
        "border": "rgb(var(--border) / <alpha-value>)",
        "text": "rgb(var(--text) / <alpha-value>)",
        "muted": "rgb(var(--muted) / <alpha-value>)",
      },
      fontFamily: {
        "code-trace": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "code-trace": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    }
  },
  plugins: []
} satisfies Config;
